# Generated by Django 6.0.4 on 2026-09-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
