# Generated by Django 6.0.4 on 2026-09-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_timeslot_patient_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'start_time', 'doctor_name'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='doctor_name',
            field=models.CharField(default='Dr. Sarah Jenkins', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'start_time', 'doctor_name')},
        ),
    ]
