# Generated by Django 6.0.4 on 2026-09-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_alter_timeslot_options_timeslot_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='booked_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
