# Generated by Django 6.0.4 on 2026-09-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0004_timeslot_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='receptionist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
